export function generatePakistaniNumberVariants(input) {
    // Remove spaces, dashes, parentheses
    let clean = input.replace(/[\s-()]/g, "");
  
    // Normalize (remove + if present)
    if (clean.startsWith("+")) {
      clean = clean.substring(1);
    }
  
    let variants = new Set();
  
    if (clean.startsWith("92")) {
      // International format
      const withoutCode = clean.substring(2); // remove 92
      variants.add("0" + withoutCode);          // 0300...
      variants.add(withoutCode);                // 300...
      variants.add("92" + withoutCode);         // 92300...
      variants.add("+92" + withoutCode);        // +92300...
      variants.add("0" + clean.substring(2));   // +920300...
      variants.add("92" + "0" + withoutCode);   // 920300...
      variants.add("+92" + "0" + withoutCode);  // +920300...
    } else if (clean.startsWith("0")) {
      // Local format
      const withoutZero = clean.substring(1);
      variants.add(clean);                       // 0300...
      variants.add(withoutZero);                 // 300...
      variants.add("92" + withoutZero);          // 92300...
      variants.add("+92" + withoutZero);         // +92300...
      variants.add("92" + clean);                // 920300...
      variants.add("+92" + clean);               // +920300...
    } else {
      // Just digits like 3001234567
      variants.add(clean);                       // 300...
      variants.add("0" + clean);                 // 0300...
      variants.add("92" + clean);                // 92300...
      variants.add("+92" + clean);               // +92300...
      variants.add("92" + "0" + clean);          // 920300...
      variants.add("+92" + "0" + clean);         // +920300...
    }
  
    return [...variants]; // return as array
  }
  
